**Mahmoud Mohammadi (mmoahm12@uncc) **

In [1]:
import tensorflow as tf

from sklearn import datasets
from sklearn.model_selection import train_test_split

from sklearn.metrics import accuracy_score


from tensorflow.contrib.layers import fully_connected
import time
import numpy as np

** Using IRIS dataset from SKLearn **

In [122]:
iris = datasets.load_iris()

print( iris.keys(), iris['target_names'],iris['feature_names'])

dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names']) ['setosa' 'versicolor' 'virginica'] ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [115]:
a=[1,2,3,4,5,6,]
b=[10,20,30,40,50,60]

np.random.seed(100000)
#idx = np.random.permutation(len(a))
#print(idx)
#a,b = a[idx], b[idx]

np.random.shuffle(a)
print(a)

np.random.seed(100000)
np.random.shuffle(b)
print(b)

[1, 6, 4, 5, 3, 2]
[10, 60, 40, 50, 30, 20]


In [124]:
data= iris['data']
y = iris['target']
np.random.seed(100000)
np.random.shuffle(data)
np.random.seed(100000)
np.random.shuffle(y)
data ,y

(array([[ 5.5,  2.3,  4. ,  1.3],
        [ 6. ,  3.4,  4.5,  1.6],
        [ 6. ,  3. ,  4.8,  1.8],
        [ 5.9,  3. ,  4.2,  1.5],
        [ 4.4,  3. ,  1.3,  0.2],
        [ 4.4,  2.9,  1.4,  0.2],
        [ 5.1,  3.4,  1.5,  0.2],
        [ 4.9,  3. ,  1.4,  0.2],
        [ 6.4,  2.8,  5.6,  2.1],
        [ 5.7,  4.4,  1.5,  0.4],
        [ 5. ,  3.2,  1.2,  0.2],
        [ 5.8,  2.7,  3.9,  1.2],
        [ 4.9,  2.4,  3.3,  1. ],
        [ 6.1,  2.9,  4.7,  1.4],
        [ 5.2,  3.5,  1.5,  0.2],
        [ 6.5,  3. ,  5.8,  2.2],
        [ 5.1,  3.7,  1.5,  0.4],
        [ 5.6,  2.5,  3.9,  1.1],
        [ 6.6,  3. ,  4.4,  1.4],
        [ 5. ,  3.6,  1.4,  0.2],
        [ 6. ,  2.2,  4. ,  1. ],
        [ 4.3,  3. ,  1.1,  0.1],
        [ 6.1,  2.6,  5.6,  1.4],
        [ 5. ,  3.4,  1.6,  0.4],
        [ 4.4,  3.2,  1.3,  0.2],
        [ 5.7,  2.9,  4.2,  1.3],
        [ 5.1,  2.5,  3. ,  1.1],
        [ 6.9,  3.2,  5.7,  2.3],
        [ 7.9,  3.8,  6.4,  2. ],
        [ 6.5,

In [7]:
iris['data'][:5] 

array([[ 5.1,  3.5,  1.4,  0.2],
       [ 4.9,  3. ,  1.4,  0.2],
       [ 4.7,  3.2,  1.3,  0.2],
       [ 4.6,  3.1,  1.5,  0.2],
       [ 5. ,  3.6,  1.4,  0.2]])

In [72]:
labels = iris['target']
np.random.seed(100000)
np.random.shuffle(labels)
labels

array([0, 2, 2, 0, 1, 2, 1, 0, 0, 2, 1, 1, 2, 1, 1, 2, 0, 0, 0, 0, 0, 0, 2,
       0, 0, 2, 2, 0, 1, 2, 2, 2, 1, 2, 0, 0, 2, 0, 1, 2, 1, 0, 1, 1, 2, 2,
       2, 0, 0, 2, 0, 1, 2, 0, 1, 2, 0, 2, 2, 2, 1, 1, 1, 1, 0, 0, 1, 2, 0,
       2, 1, 1, 1, 2, 2, 0, 2, 1, 0, 0, 0, 1, 1, 0, 2, 2, 0, 1, 1, 2, 1, 2,
       2, 1, 2, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 2, 1, 2, 1, 1, 1, 1, 2, 2,
       0, 2, 1, 1, 0, 0, 0, 2, 2, 2, 0, 2, 1, 2, 1, 0, 0, 1, 2, 2, 1, 2, 0,
       0, 2, 0, 0, 2, 1, 0, 0, 1, 1, 1, 0])

In [10]:
iris['feature_names']

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

** NN_Model: Neural Network Class implementing the NN model wiht model building and training functions**

**__init__** : initializing the class parameters such as number of inputs , number of outputs, neurons ...

**build_model**: Building a simple NN model consisting:

1. Model

    1. Input Layer: 4*n inputs layer because the IRIS data ( as training data) has 4 features as:    
    
       - 'sepal length (cm)',
     
       - 'sepal width (cm)',
    
       - 'petal length (cm)',
    
       - 'petal width (cm)'      
    
    2. One Hidden Layer (with ReLU activation)
    
        - using Tensorflow [fully_connected](  https://www.tensorflow.org/api_docs/python/tf/contrib/layers/fully_connected) API
            - **Weights** : Fully connected weight matrix, which is multiplied by the inputs( in each layer)
            - **Activation function**: The default value is a ReLU function            
            - **Biases** : Zero tensor            
    
    3. Output Layer:  without Activation function with dimention of n*3 because the IRIS labels has 3 classes
    
2. Loss Function
   -  Average (mean) of ** sparse_softmax_cross_entropy_with_logits()** on logits
    
3. Training : 
    - Opitmizer : **GradientDescentOptimizer()**
    

In [144]:
class NN_Model(object):
    def __init__(self, sess, n_inputs, n_outputs, n_hidden, \
                 n_neurons, scope, epoch, batch_size, learning_rate):

        self.n_inputs= n_inputs
        self.n_classes= n_outputs
        self.n_hidden = n_hidden
        self.n_neurons = n_neurons
        
        self.scope= scope
        
        self.epoch = epoch
        self.batch_size = batch_size
        
        self.learning_rate= learning_rate
        
        self.sess = sess
        
        # Partitioning the dataset  
        X_data , y_labels, y_onehot = self.load_dataset('iris')
        
        print(" Data: %s ,  Target: %s , OneHot: %s " %(X_data.shape , y_labels.shape ,y_onehot.shape ))
        
        self.X_train, self.X_test, self.y_train, self.y_test \
            = train_test_split( X_data , y_labels, test_size = 0.3)
            
        
        self.build_model()
       
            #iris['data'] , iris['target'].reshape((-1,1)),test_size = 0.3)

    def load_dataset(self, dataset_name):
        
        # Loading IRIS  datafiles (CSV)
        dataset = datasets.load_iris()
        
        data =dataset['data']
        
        seed= 8000
        tf.random_shuffle(data, seed=seed)
        
                        
        y = dataset['target']               
        y = y.reshape(y.shape[0])  
        
        tf.random_shuffle(y, seed=seed)
        
        y_onehot = np.zeros( (len(y) , self.n_classes), dtype=np.float)        
        for i, _ in enumerate(y):
            y_onehot[i, y[i]] = 1.0
    
        
        return data, y , y_onehot
       
    
    def make_layer(self, X, n_neurons , activation_fn="relu"):
        
        with tf.name_scope(self.scope):
            n_inputs =(int)(X.shape[1])

            init_w = tf.truncated_normal(shape=(n_inputs, n_neurons))
            
            W = tf.Variable(init_w , name="Weights")
            b = tf.Variable(tf.zeros([n_neurons]), name="bias")

            y = tf.matmul(X, W) + b

            if activation_fn == "relu":
                return tf.nn.relu(y)
            else:
                return y
  
    def build_model(self):
        
        with tf.name_scope(self.scope) :
            
            inputs_dim= [self.n_inputs]
            
            y_dim = []
            
            #self.batch_size
            # Defining Input Data Placeholders            
            self.inputs= tf.placeholder(tf.float32, shape=[None] + inputs_dim,  name='inputs')
            
            self.y = tf.placeholder(tf.int32, shape=[None] + y_dim, name='y')

          
            
            # Input Layer with ReLU Activation function as default            
            inputs = fully_connected(self.inputs, self.n_neurons )
            
            #inputs = self.make_layer(self.X_train, self.n_neurons )
            
            print("inputs %s " %(inputs.shape ))
            
            
            # Hidden Layer with ReLU Activation function as default 
            hidden1 = fully_connected(inputs, self.n_neurons )
            #hidden1 = self.make_layer(inputs, self.n_neurons )
            
            print("Hidern 1 %s " %(hidden1.shape))
            

            # Last Layer of model without applying Activation function: Logits
            logits = fully_connected(hidden1, self.n_classes, activation_fn=None)  
            #logits = self.make_layer(hidden1, self.n_classes, activation_fn=None)  
            print("Logits %s , Label %s" %(logits.shape , self.y.shape))
            
            
            # Defining Loss function based on Entropy
            
            #xentropy = tf.nn.sigmoid_cross_entropy_with_logits(labels= self.y , logits= logits)
            
            xentropy = tf.nn.sparse_softmax_cross_entropy_with_logits(logits= logits ,labels= self.y )

            self.loss = tf.reduce_mean(xentropy, name="loss") # Average of all logits
            
            self.saver = tf.train.Saver()
            
            
            
            # Evaluation of Logits            
            evals = tf.nn.in_top_k(tf.cast(logits , tf.float32), self.y, 1)
            
            self.accuracy = tf.reduce_mean( tf.cast(evals , tf.float32))

        

    def train(self):
        print("Start Training...\n")
        
        #Optimizer        
        optimizer = tf.train.GradientDescentOptimizer(self.learning_rate).minimize(self.loss)
        
        #Initializing the Global Variables       
        tf.global_variables_initializer().run(session= self.sess)
        
        #Calculating Number of batches                    
        num_batches = len(self.X_train) // self.batch_size 
        
         
        start_time = time.time()
        
        for epoch in range(self.epoch):
            
            #print("Epoch Index"+ epoch)
            
            for idx in range(num_batches):
                
                #print("Batch Index"+ idx)
                
                batch_data = self.X_train[idx *  self.batch_size: (idx+1) *  self.batch_size] 
                batch_labeles= self.y_train[idx *  self.batch_size: (idx+1) *  self.batch_size] 
                
                print("Batch Data %s , Batch Label %s" %(batch_data.shape , batch_labeles.shape))
                
                with self.sess.as_default():
                    
                    self.sess.run([optimizer],
                        feed_dict={self.inputs: batch_data, 
                                   self.y:      batch_labeles  
                                  })
                
                    acc_train = self.accuracy.eval( feed_dict={
                    self.inputs: batch_data, 
                    self.y:      batch_labeles  
                     })
                
                    acc_test  = self.accuracy.eval( feed_dict={
                    self.inputs: self.X_test, 
                    self.y:      self.y_test  
                                                          
                    })
                   
                print("Dataset:[%s] -> Epoch: [%2d][%4d/%4d] time: %4.4f, Acu Train: %.8f Acu Test: %.8f"
                      % ('iris', epoch, idx, num_batches,
                         time.time() - start_time, acc_train, acc_test))
                
           
    

In [152]:
#def main():
    
with tf.Session() as sess:
        nn_obj = NN_Model(
            sess,
            scope = 'Test', 
            epoch = 25, 
            n_inputs = 4, 
            n_outputs = 3,
            n_hidden = 1, # Changing this paramater has no effect
            n_neurons = 5,           
            batch_size= 5, 
            learning_rate = 0.01
            )
        
nn_obj.train()

 Data: (150, 4) ,  Target: (150,) , OneHot: (150, 3) 
inputs (?, 5) 
Hidern 1 (?, 5) 
Logits (?, 3) , Label (?,)


** One sample of Execution Results with different values for Neurons, Batch Size and Learning Rate **

** Rerunnig the model using the same parameters may generate different results!**

| Neurons | Batch Size |  Learnign Rate | Train Accuracy % | Test Accuracy % |
|---------|------------|----------------|------------------|-----------------|
| 5       | 10         | 0.01           | 63.8             | 66.6            |
| 5       | 10         | 0.1            | 91.4             | 91.4            |
| 5       | 20         | 0.01           | 69.5             | 69.5            |
| 5       | 20         | 0.1            | 71               | 71              |
| 10      | 10         | 0.01           | 89.5             | 89.5            |
| 10      | 10         | 0.1            | 97.1             | 97.1            |
| 10      | 20         | 0.01           | 87.6             | 87.6            |
| 10      | 20         | 0.1            | 84.7             | 84.7            |